FROM  git.quavlive.com:5052/wb-phd/code/rl_lab

# Add the ROS 2 apt repository
RUN apt update && apt install -y curl gnupg2 lsb-release
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive && \
    apt install -y ros-foxy-desktop

WORKDIR /root/catkin_ws/src
RUN git clone https://github.com/ros/ros_tutorials.git -b foxy-devel
WORKDIR /root/catkin_ws

RUN apt update && \
    apt-get install python3-rosdep -y && \
    rosdep init && \
    rosdep update && \
    rosdep install -i --from-path src --rosdistro foxy -y && \
    apt install python3-colcon-common-extensions -y

RUN apt update && \
    apt install ros-foxy-rmw-cyclonedds-cpp -y && \
    apt install iputils-ping && \
    pip install pyglet

RUN pip3 install opencv-python

RUN apt install swig -y && \
    pip install gym[box2d]

COPY ./ros_entrypoint.sh /root
ENTRYPOINT ["/root/ros_entrypoint.sh"]
CMD ["bash"]
