teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.

    axis_angular:  # Left thumb stick horizontal
      yaw: 2
    scale_angular:
      yaw: 1.

    enable_button: 4  # Left trigger button
    enable_turbo_button: 5  # Right trigger button


## Axis
# 0 = Left H
# 1 = Left V
# 2 = Right H
# 3 = Right V

## Button
# 0 = X
# 1 = A
# 2 = B
# 3 = Y
# 4 = LB
# 5 = RB
# 6 = LT
# 7 = RT
# 8 = Back
# 9 = Start
# 10 = Left joy click
# 11 = Right joy click